/**
 * Official Copy Deck dictionary for US Solar Calculator
 * Strictly follows §11 of the UX/UI Specification — no edits, no paraphrasing.
 */
export const STRINGS = {
  // 11.1 Main Page
  h1Title: "Power your home with clean energy",
  subtitle: "Enter your address for an instant solar assessment — production, savings and panel layout from high-resolution aerial imagery of your actual roof.",
  promisedResults: ["Annual production", "Yearly savings", "Payback time"],
  overviewMapCaption: "The US gets abundant solar potential. We survey your actual roof once you enter an address.",
  addressLabel: "Your address",
  addressPlaceholder: "e.g. 1600 Amphitheatre Pkwy, Mountain View, CA",
  clearAddressBtn: "Clear address",
  useMyLocationBtn: "Use my current location",
  monthlyBillLabel: "Your average monthly electricity bill",

  // 11.2 Loading Stages
  loadingStage1: "Finding your address…",
  loadingStage2: "Reading your roof from aerial imagery…",
  loadingStage3: "Measuring sunlight hour by hour…",

  // 11.3 Map & Marker
  mapAdjustHint: "Not your roof? Double-click your roof on the map (or drag the pin) to adjust.",
  gotItBtn: "Got it",
  pinTitle: "Your roof location — drag to adjust",
  noRoofDataError: "No roof data found at this point — try clicking directly on the building.",
  nearestBuildingMatch: "Matched the nearest building — is this your roof?",
  chipSurveyImagery: "Survey imagery",
  chipEditLayout: "Edit layout",
  chipSunExposure: "Sun exposure",
  view3d: "3D view",
  view2d: "2D view",
  resetView: "Reset view",
  orbitHint: "Drag to orbit · scroll to zoom",
  heatmapIn2dNotice: "Sun-exposure heatmap is available in the 2D top-down view.",

  // 11.4 Layout
  layoutGroupLabel: "Layout",
  layoutNames: {
    standard: "Standard",
    eastWest: "East–West",
    canopy: "Canopy",
  },
  layoutBenefits: {
    standard: "Highest yield per panel",
    eastWest: "Most panels, steadier output",
    canopy: "Covers obstacles, adds shade",
  },
  layoutDescriptions: {
    standard: "South-facing tilted rows for suitable flat roof areas.",
    eastWest: "More consistent production through the day, better self-consumption.",
    canopy: "Adds usable shaded space below; higher installation cost.",
  },
  editor: {
    select: "Select",
    paintPlus: "Paint +",
    paintMinus: "Paint −",
    undo: "Undo",
    redo: "Redo",
    enable: "Enable",
    disable: "Disable",
    deleteRow: "Delete row",
    selected: "selected",
    rotate: "Rotate",
    arrayRotation: "Array rotation",
    holdShiftHint: "Hold Shift for 1° steps",
    optimal: "Optimal",
    resetRotationTooltip: "Reset rotation to the auto-computed optimal orientation",
    toolsGroup: "Tools",
    historyGroup: "History",
    rowsGroup: "Rows",
    roofRow: "Roof",
    southRow: "South",
    alignRoofTooltip: "Align rows to the roof's own edges — usually fits more panels",
    alignSouthTooltip: "Face rows due south for the best aspect — may fit fewer panels",
  },
  customLayoutBadge: "custom layout",
  resetLayoutBtn: "Reset layout",

  // 11.5 Results
  estAnnualProduction: "Estimated annual production",
  estAnnualSavings: "Estimated annual savings",
  systemSize: "System size",
  simplePayback: "Simple payback",
  fastRoiBadge: "Fast ROI",
  usableRoofArea: "Usable roof area",
  sunshinePerYear: "Sunshine per year",
  imagery: "Imagery",
  panels: "Panels",
  howWeCalculatedThis: "How we calculated this",
  outlook25Year: "25-year outlook",
  cumulativeSavingsHeader: "Cumulative savings over 25 years",
  netCumulativeBenefit: "Net cumulative benefit",
  paybackYear: "Payback year",
  co2Avoided: "CO₂ avoided",
  yearLabel: "Year",
  resultsDisclaimer: "Estimates only, based on aerial imagery and standard assumptions — not a binding quote. A site visit confirms final design and pricing.",

  // 11.6 System & Equipment
  systemType: "System type",
  gridTie: "Grid-Tie",
  hybridBattery: "Hybrid + Battery",
  batteryStorage: "Battery storage",
  none: "None",
  evChargingPoint: "EV charging point",
  energyUsedAtHome: "Energy used at home",
  surplusChargesNotice: "Surplus charges a battery for use after dark, so more of your production offsets full utility rates.",
  selectedStorageRecommendation: "Selected {N} kWh · roof recommendation {M} kWh",
  selectedStorageOptional: "Selected {N} kWh · storage is optional for this load profile",
  recommendedStorage: "Recommended {M} kWh for this roof and usage",
  usageAbsorbsNotice: "Your usage already absorbs production during the day — a battery would rarely charge.",
  lowSurplusNotice: "Only about {N} kWh a day is left over — less than the smallest battery we fit, so it would never fill.",
  sec25dUnavailable: "Residential Section 25D is unavailable for new installations completed after 2025.",
  sec48eApplied: "✓ {N}% Section 48E credit applied subject to tax eligibility.",
  commercialCreditDisabled: "Commercial tax credit disabled for this estimate.",

  // 11.7 Simple Card
  simpleCardTitle: "Solar Assessment Summary",
  simpleCardSubtext: "Optimal solar system configuration for your building",
  recommendedCapacity: "Recommended Capacity",
  optimalRooftopSize: "Optimal rooftop system size",
  annualSavings: "Annual Savings",
  estBillSavings: "Estimated electricity bill savings",
  includesIncentives: "Includes the selected incentive assumptions",
  getProposalCta: "Get Your Official Proposal & 3D Model →",
  customizeInProLink: "Customize panel layout manually (Pro Sales Mode)",

  // 11.8 Lead Form
  getFullProposal: "Get your full proposal",
  leadFormSubtext: "We'll review your roof and send a detailed quote within 2 working days.",
  nameLabel: "Name",
  emailLabel: "Email",
  phoneLabel: "Phone",
  consentLabel: "I agree to be contacted about this solar assessment.",
  requestQuoteBtn: "Request my quote",
  requestReceivedSuccess: "Request received — we'll be in touch shortly.",

  // 11.9 Proposal Report
  preliminaryProposalBadge: "Preliminary proposal",
  printSavePdfBtn: "Print / Save PDF",
  unlockPdfHint: "Add your email & phone below to unlock the PDF",
  backToCalculator: "← Back to calculator",
  dateLabel: "Date",
  roofAnalysisSection: "Roof analysis",
  recommendedSystemSection: "Recommended system",
  assumptionsDisclaimersSection: "Assumptions & disclaimers",
  pendingVerificationBadge: "pending verification",
  nextStepsSection: "Next steps",
  viewFullReportBtn: "View full report",
  reportEngineeringDisclaimer: "This is not an engineering design — structural assessment, wiring and final layout are confirmed on-site.",
  exposureSunHeader: "Sun exposure under the array",
  exposureSunText: "Panels are placed on the highest-yield areas of your roof — the heatmap shows measured annual sunlight beneath the layout.",
  renderingSunImage: "Rendering your roof's sun-exposure image…",
  couldNotRenderSunImage: "Couldn't render the sun-exposure image.",
  tryAgainBtn: "Try again",
  nextStep1: "Request your full proposal — we review the imagery analysis and confirm component pricing.",
  nextStep2: "Free site visit: structural check, shading survey, and final panel layout.",
  nextStep3: "Installation and eligible incentive documentation, handled end-to-end.",

  // 11.10 Errors & Crashes
  noSolarDataError: "We couldn't find solar data for this address yet. Leave your details and we'll assess your roof manually — free of charge.",
  fetchAssessmentError: "Something went wrong fetching the assessment. Please try again, or leave your details for a manual assessment.",
  crashTitle: "Something went wrong",
  crashText: "The assessment couldn't finish. This is a fault on our side, not with your address.",
  copyErrorDetails: "Copy error details",
  techDetails: "Technical details",
  estimatesUnavailable: "Estimates are temporarily unavailable",
};
